from libs.car_description import CarDescription
from libs.normalise_angle import normalise_angle
from libs.cubic_spline_interpolator import generate_cubic_spline
from libs.stanley_controller import StanleyController